# Generated by Django 4.2.4 on 2024-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LipskiPublikuje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('finanse', 'Finanse'), ('sztuka', 'Sztuka'), ('ciekawostki', 'Ciekawostki'), ('polityka', 'Polityka')], default='ciekawostki', max_length=20),
        ),
    ]
