# Generated by Django 4.2.4 on 2024-03-18 15:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LipskiPublikuje', '0002_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
