# Generated by Django 4.2.4 on 2024-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LipskiPublikuje', '0003_alter_articles_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
