# Generated by Django 4.2.4 on 2024-03-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LipskiPublikuje', '0009_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='social_facebook',
            field=models.URLField(default='https://www.facebook.com'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_git',
            field=models.URLField(default='https://www.github.com'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='social_twitter',
            field=models.URLField(default='https://www.twitter.com'),
        ),
    ]
